CREATE TABLE pengunjung (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  no INT NOT NULL,
  nama VARCHAR(100) NOT NULL,
  notlp VARCHAR(20) NOT NULL,
  instansi VARCHAR(100) NOT NULL,
  keperluan VARCHAR(20) NOT NULL,
  tanggal DATE NOT NULL,
  jam TIME NOT NULL,
  status VARCHAR(50) NOT NULL
);